package codegen

import (
	"context"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"

	"github.com/Eisenmann/openapi-mocker/internal/domain/ports"
)

// CSharpNativeAdapter generates C# server and client code natively from an
// OpenAPI contract, without external tooling. It implements
// ports.CodeGeneratorPort.
type CSharpNativeAdapter struct{}

// NewCSharpNativeAdapter creates a C# native adapter.
func NewCSharpNativeAdapter() *CSharpNativeAdapter {
	return &CSharpNativeAdapter{}
}

// Supports reports whether this adapter supports the given language.
func (a *CSharpNativeAdapter) Supports(lang ports.Language) bool {
	return lang == ports.LanguageCSharp
}

// Strategy returns the generation strategy used by this adapter.
func (a *CSharpNativeAdapter) Strategy() ports.GenerationStrategy {
	return ports.StrategyNative
}

// Generate produces C# server and client files from the OpenAPI schema.
func (a *CSharpNativeAdapter) Generate(
	ctx context.Context,
	req *ports.GenerationRequest,
) (*ports.GenerationResult, error) {
	doc, err := parseAndValidate(ctx, req.Schema.Content)
	if err != nil {
		return nil, err
	}

	pkgName := req.PackageName
	if pkgName == "" {
		pkgName = defaultPackageName
	}

	// Generate server files.
	serverFiles := generateCSServer(doc, pkgName)

	// Generate client file.
	clientFiles := generateCSClient(doc, pkgName)

	// Combine into GeneratedFile list.
	var files []ports.GeneratedFile
	for name, content := range serverFiles {
		files = append(files, ports.GeneratedFile{
			Path:    req.OutputPath + "/server/" + name,
			Content: []byte(content),
			IsNew:   true,
		})
	}

	for name, content := range clientFiles {
		files = append(files, ports.GeneratedFile{
			Path:    req.OutputPath + "/client/" + name,
			Content: []byte(content),
			IsNew:   true,
		})
	}

	// Generate .csproj.
	csproj := generateCSCSProj(pkgName)

	files = append(files, ports.GeneratedFile{
		Path:    req.OutputPath + "/" + pkgName + ".csproj",
		Content: []byte(csproj),
		IsNew:   true,
	})

	// Generate README.md.
	readme := generateCSReadme(pkgName)

	files = append(files, ports.GeneratedFile{
		Path:    req.OutputPath + "/README.md",
		Content: []byte(readme),
		IsNew:   true,
	})

	return &ports.GenerationResult{
		Files:      files,
		Language:   ports.LanguageCSharp,
		Strategy:   ports.StrategyNative,
		Warnings:   []string{},
		CICDConfig: nil,
	}, nil
}

// generateCSServer returns a set of files (name → content) with a C# HTTP
// server skeleton using the standard library HttpListener.
func generateCSServer(doc *openapi3.T, _ string) map[string]string {
	ops := collectOperations(doc)

	return map[string]string{
		"ServerInterface.cs":     generateCSInterface(ops),
		"Router.cs":              generateCSRouter(ops),
		"UnimplementedServer.cs": generateCSUnimplemented(ops),
		"Program.cs":             generateCSProgram(),
	}
}

// generateCSInterface produces the ServerInterface C# file.
func generateCSInterface(ops []operationInfo) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	b.WriteString("using System.Net;\n\n")
	b.WriteString("// ServerInterface - implement this interface with your business logic.\n")
	b.WriteString("public interface ServerInterface\n{\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "    // %s %s %s\n", op.OpID, op.Method, op.Path)
		fmt.Fprintf(&b, "    void %s(HttpListenerContext ctx);\n", toCSIdent(op.OpID))
	}

	b.WriteString("}\n")

	return b.String()
}

// generateCSRouter produces the router C# file.
func generateCSRouter(ops []operationInfo) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	b.WriteString("using System.Net;\n\n")
	b.WriteString("// NewRouter registers all contract operations on the ServerInterface implementation.\n")
	b.WriteString("public static class Router\n{\n")
	b.WriteString("    public static void Handle(HttpListenerContext ctx, ServerInterface impl)\n")
	b.WriteString("    {\n")
	b.WriteString("        var method = ctx.Request.HttpMethod.ToUpperInvariant();\n")
	b.WriteString("        var path = ctx.Request.Url.AbsolutePath;\n\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "        if (method == %q && path.StartsWith(%q))\n", op.Method, op.Path)
		b.WriteString("        {\n")
		fmt.Fprintf(&b, "            impl.%s(ctx);\n", toCSIdent(op.OpID))
		b.WriteString("            return;\n")
		b.WriteString("        }\n\n")
	}

	b.WriteString("        ctx.Response.StatusCode = 404;\n")
	b.WriteString("        ctx.Response.ContentType = \"application/json\";\n")
	b.WriteString("        var bytes = System.Text.Encoding.UTF8.GetBytes(\"{\\\"error\\\": \\\"not found\\\"}\");\n")
	b.WriteString("        ctx.Response.OutputStream.Write(bytes, 0, bytes.Length);\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return b.String()
}

// generateCSUnimplemented produces the sample implementation C# file.
func generateCSUnimplemented(ops []operationInfo) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. THIS IS A SAMPLE implementation - customize for your needs.\n")
	b.WriteString("using System.Net;\n")
	b.WriteString("using System.Text;\n\n")
	b.WriteString("public class UnimplementedServer : ServerInterface\n{\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "    public void %s(HttpListenerContext ctx)\n", toCSIdent(op.OpID))
		b.WriteString("    {\n")
		b.WriteString("        ctx.Response.StatusCode = 501;\n")
		b.WriteString("        ctx.Response.ContentType = \"application/json\";\n")
		fmt.Fprintf(&b, "        var body = \"{\\\"error\\\": \\\"%s not implemented\\\"}\";\n", op.OpID)
		b.WriteString("        var bytes = Encoding.UTF8.GetBytes(body);\n")
		b.WriteString("        ctx.Response.OutputStream.Write(bytes, 0, bytes.Length);\n")
		b.WriteString("    }\n\n")
	}

	b.WriteString("}\n")

	return b.String()
}

// generateCSProgram produces the example server startup C# file.
func generateCSProgram() string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. Example server startup.\n")
	b.WriteString("using System;\n")
	b.WriteString("using System.Net;\n\n")
	b.WriteString("class Program\n")
	b.WriteString("{\n")
	b.WriteString("    static void Main()\n")
	b.WriteString("    {\n")
	b.WriteString("        var listener = new HttpListener();\n")
	b.WriteString("        listener.Prefixes.Add(\"http://localhost:8081/\");\n")
	b.WriteString("        listener.Start();\n")
	b.WriteString("        Console.WriteLine(\"listening on :8081\");\n\n")
	b.WriteString("        var impl = new UnimplementedServer();\n")
	b.WriteString("        while (true)\n")
	b.WriteString("        {\n")
	b.WriteString("            var ctx = listener.GetContext();\n")
	b.WriteString("            Router.Handle(ctx, impl);\n")
	b.WriteString("            ctx.Response.Close();\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return b.String()
}

// generateCSClient returns a set of files with a type-safe (by path and
// method) HTTP client for the contract.
func generateCSClient(doc *openapi3.T, _ string) map[string]string {
	ops := collectOperations(doc)

	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	b.WriteString("using System;\n")
	b.WriteString("using System.Collections.Generic;\n")
	b.WriteString("using System.Net.Http;\n")
	b.WriteString("using System.Text;\n")
	b.WriteString("using System.Threading.Tasks;\n\n")
	b.WriteString("public class Client\n")
	b.WriteString("{\n")
	b.WriteString("    private readonly HttpClient _http;\n")
	b.WriteString("    private readonly string _baseUrl;\n\n")
	b.WriteString("    public Client(string baseUrl)\n")
	b.WriteString("    {\n")
	b.WriteString("        _baseUrl = baseUrl.TrimEnd('/');\n")
	b.WriteString("        _http = new HttpClient();\n")
	b.WriteString("    }\n\n")
	b.WriteString("    private async Task<HttpResponseMessage> Do(string method, string path, " +
		"Dictionary<string, string> pathParams, string body = null)\n")
	b.WriteString("    {\n")
	b.WriteString("        var url = path;\n")
	b.WriteString("        foreach (var kv in pathParams)\n")
	b.WriteString("        {\n")
	b.WriteString("            url = url.Replace(\"{\" + kv.Key + \"}\", kv.Value);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        var request = new HttpRequestMessage(new HttpMethod(method), _baseUrl + url);\n")
	b.WriteString("        if (body != null)\n")
	b.WriteString("        {\n")
	b.WriteString("            request.Content = new StringContent(body, Encoding.UTF8, \"application/json\");\n")
	b.WriteString("        }\n\n")
	b.WriteString("        return await _http.SendAsync(request);\n")
	b.WriteString("    }\n\n")

	for _, op := range ops {
		writeCSClientMethod(&b, op)
	}

	b.WriteString("}\n")

	return map[string]string{"Client.cs": b.String()}
}

// writeCSClientMethod writes a single client method for an operation.
func writeCSClientMethod(b *strings.Builder, op operationInfo) {
	pathParamsNeeded := extractPathParams(op.Path)
	fmt.Fprintf(b, "    // %s corresponds to %s %s\n", toCSIdent(op.OpID), op.Method, op.Path)

	if hasBody(op.Method) {
		fmt.Fprintf(b, "    public async Task<HttpResponseMessage> %s("+
			"Dictionary<string, string> pathParams, string body = null)\n", toCSIdent(op.OpID))
	} else {
		fmt.Fprintf(b, "    public async Task<HttpResponseMessage> %s("+
			"Dictionary<string, string> pathParams = null)\n", toCSIdent(op.OpID))
	}

	b.WriteString("    {\n")

	if len(pathParamsNeeded) > 0 {
		fmt.Fprintf(b, "        // required path parameters: %s\n", strings.Join(pathParamsNeeded, ", "))
	}

	if hasBody(op.Method) {
		fmt.Fprintf(b, "        return await Do(%q, %q, pathParams ?? "+
			"new Dictionary<string, string>(), body);\n", op.Method, op.Path)
	} else {
		fmt.Fprintf(b, "        return await Do(%q, %q, pathParams ?? "+
			"new Dictionary<string, string>());\n", op.Method, op.Path)
	}

	b.WriteString("    }\n\n")
}

// generateCSCSProj produces a .csproj for the generated project.
func generateCSCSProj(pkgName string) string {
	return fmt.Sprintf(`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>%s</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
`, pkgName)
}

// generateCSReadme produces a README.md for the generated project.
func generateCSReadme(pkgName string) string {
	return fmt.Sprintf(`# %s

Generated by openapi-mocker.

## Server

Run the example server:

`+"```bash"+`
dotnet run
`+"```"+`

## Client

Use the generated client:

`+"```csharp"+`
var client = new Client("http://localhost:8081");
var response = await client.GetPets(new Dictionary<string, string>());
`+"```"+`
`, pkgName)
}

// toCSIdent converts a string to a valid C# identifier.
func toCSIdent(s string) string {
	out := toGoIdent(s)
	if out == "" {
		return defaultOperationName
	}

	return out
}
