// Package codegen is the adapter implementing usecase.CodeGenerator: generates
// a minimal but functional Go server and Go client skeleton from an OpenAPI
// contract. A simple self-contained implementation with no external
// dependencies (unlike oapi-codegen/openapi-generator), keeping the application
// self-contained. For richer typed generation
// (oneOf/allOf, DTO) this is a good extension point — the
// usecase.CodeGenerator interface can be implemented differently without
// touching anything above.
package codegen

import (
	"context"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"

	"github.com/Eisenmann/openapi-mocker/internal/usecase"
)

type Generator struct{}

func NewGenerator() *Generator { return &Generator{} }

var _ usecase.CodeGenerator = (*Generator)(nil)

func (g *Generator) GenerateServerZip(raw []byte, pkgName string) ([]byte, error) {
	doc, err := parseAndValidate(raw)
	if err != nil {
		return nil, err
	}
	return toZip(generateGoServer(doc, pkgName))
}

func (g *Generator) GenerateClientZip(raw []byte, pkgName string) ([]byte, error) {
	doc, err := parseAndValidate(raw)
	if err != nil {
		return nil, err
	}
	return toZip(generateGoClient(doc, pkgName))
}

func parseAndValidate(raw []byte) (*openapi3.T, error) {
	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = false
	doc, err := loader.LoadFromData(raw)
	if err != nil {
		return nil, fmt.Errorf("failed to parse contract: %w", err)
	}
	if err := doc.Validate(context.Background()); err != nil {
		return nil, fmt.Errorf("contract failed validation: %w", err)
	}
	return doc, nil
}

type operationInfo struct {
	OpID   string // safe Go identifier name.
	Method string
	Path   string // /users/{id}.
}

func collectOperations(doc *openapi3.T) []operationInfo {
	var ops []operationInfo
	if doc.Paths == nil {
		return ops
	}
	for path, item := range doc.Paths.Map() {
		for method, op := range item.Operations() {
			id := op.OperationID
			if id == "" {
				id = method + "_" + path
			}
			ops = append(ops, operationInfo{OpID: toGoIdent(id), Method: strings.ToUpper(method), Path: path})
		}
	}
	sort.Slice(ops, func(i, j int) bool {
		if ops[i].Path != ops[j].Path {
			return ops[i].Path < ops[j].Path
		}
		return ops[i].Method < ops[j].Method
	})
	return ops
}

var identSanitizer = regexp.MustCompile(`[^a-zA-Z0-9_]+`)

func toGoIdent(s string) string {
	parts := identSanitizer.Split(s, -1)
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	out := b.String()
	if out == "" {
		out = "Operation"
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "Op" + out
	}
	return out
}

// generateGoServer returns a set of files (name → content) with an HTTP server
// skeleton on the standard library: an interface with one method per
// operation + a router that calls your implementation of the interface.
func generateGoServer(doc *openapi3.T, pkgName string) map[string]string {
	ops := collectOperations(doc)
	files := map[string]string{}

	var iface strings.Builder
	fmt.Fprintf(&iface, "// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n"+
		"package %s\n\nimport \"net/http\"\n\n", pkgName)
	iface.WriteString("// ServerInterface - implement this interface with your business logic.\n")
	iface.WriteString("type ServerInterface interface {\n")
	for _, op := range ops {
		fmt.Fprintf(&iface, "\t// %s %s %s\n", op.OpID, op.Method, op.Path)
		fmt.Fprintf(&iface, "\t%s(w http.ResponseWriter, r *http.Request)\n", op.OpID)
	}
	iface.WriteString("}\n")
	files["server_interface.go"] = iface.String()

	var router strings.Builder
	fmt.Fprintf(&router, "// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n"+
		"package %s\n\nimport \"net/http\"\n\n", pkgName)
	router.WriteString("// NewRouter registers all contract operations on the ServerInterface implementation.\n")
	router.WriteString("func NewRouter(impl ServerInterface) *http.ServeMux {\n\tmux := http.NewServeMux()\n")
	for _, op := range ops {
		fmt.Fprintf(&router, "\tmux.HandleFunc(%q, impl.%s)\n", op.Method+" "+op.Path, op.OpID)
	}
	router.WriteString("\treturn mux\n}\n")
	files["router.go"] = router.String()

	var impl strings.Builder
	fmt.Fprintf(&impl, "// Code generated by openapi-mocker. THIS IS A SAMPLE implementation - "+
		"customize for your needs.\n"+
		"package %s\n\nimport (\n\t\"encoding/json\"\n\t\"net/http\"\n)\n\n", pkgName)
	impl.WriteString("type UnimplementedServer struct{}\n\n")
	for _, op := range ops {
		fmt.Fprintf(&impl, "func (UnimplementedServer) %s(w http.ResponseWriter, r *http.Request) {\n", op.OpID)
		impl.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
		impl.WriteString("\tw.WriteHeader(http.StatusNotImplemented)\n")
		fmt.Fprintf(&impl, "\tjson.NewEncoder(w).Encode(map[string]string{\"error\": \"%s not implemented\"})\n", op.OpID)
		impl.WriteString("}\n\n")
	}
	files["unimplemented.go"] = impl.String()

	var mainFile strings.Builder
	mainFile.WriteString("// Code generated by openapi-mocker. Example server startup.\npackage main\n\n")
	fmt.Fprintf(&mainFile, "import (\n\t\"log\"\n\t\"net/http\"\n\n\tsrv \"%s\"\n)\n\n", pkgName)
	mainFile.WriteString("func main() {\n\tmux := srv.NewRouter(srv.UnimplementedServer{})\n" +
		"\tlog.Println(\"listening on :8081\")\n\tlog.Fatal(http.ListenAndServe(\":8081\", mux))\n}\n")
	files["cmd_main_example.go"] = mainFile.String()

	return files
}

// generateGoClient returns a set of files with a type-safe (by path and
// method) HTTP client for the contract.
func generateGoClient(doc *openapi3.T, pkgName string) map[string]string {
	ops := collectOperations(doc)
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n"+
		"package %s\n\n", pkgName)
	b.WriteString("import (\n\t\"bytes\"\n\t\"context\"\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"io\"\n" +
		"\t\"net/http\"\n\t\"strings\"\n)\n\n")
	b.WriteString("type Client struct {\n\tBaseURL string\n\tHTTP    *http.Client\n}\n\n")
	b.WriteString("func NewClient(baseURL string) *Client {\n" +
		"\treturn &Client{BaseURL: strings.TrimRight(baseURL, \"/\"), HTTP: http.DefaultClient}\n}\n\n")
	b.WriteString("func (c *Client) do(ctx context.Context, method, path string, pathParams map[string]string, " +
		"body interface{}) (*http.Response, []byte, error) {\n")
	b.WriteString("\tfor k, v := range pathParams {\n\t\tpath = strings.ReplaceAll(path, \"{\"+k+\"}\", v)\n\t}\n")
	b.WriteString("\tvar reader io.Reader\n\tif body != nil {\n\t\traw, err := json.Marshal(body)\n" +
		"\t\tif err != nil {\n\t\t\treturn nil, nil, err\n\t\t}\n\t\treader = bytes.NewReader(raw)\n\t}\n")
	b.WriteString("\treq, err := http.NewRequestWithContext(ctx, method, c.BaseURL+path, reader)\n")
	b.WriteString("\tif err != nil {\n\t\treturn nil, nil, err\n\t}\n")
	b.WriteString("\treq.Header.Set(\"Content-Type\", \"application/json\")\n")
	b.WriteString("\tresp, err := c.HTTP.Do(req)\n")
	b.WriteString("\tif err != nil {\n\t\treturn nil, nil, fmt.Errorf(\"request failed: %w\", err)\n" +
		"\t}\n\tdefer resp.Body.Close()\n")
	b.WriteString("\trespBody, err := io.ReadAll(resp.Body)\n")
	b.WriteString("\treturn resp, respBody, err\n}\n\n")

	for _, op := range ops {
		pathParamsNeeded := extractPathParams(op.Path)
		fmt.Fprintf(&b, "// %s corresponds to %s %s\n", op.OpID, op.Method, op.Path)
		if hasBody(op.Method) {
			fmt.Fprintf(&b, "func (c *Client) %s(ctx context.Context, pathParams map[string]string, body interface{}) "+
				"(*http.Response, []byte, error) {\n", op.OpID)
		} else {
			fmt.Fprintf(&b, "func (c *Client) %s(ctx context.Context, pathParams map[string]string) "+
				"(*http.Response, []byte, error) {\n", op.OpID)
		}
		if len(pathParamsNeeded) > 0 {
			fmt.Fprintf(&b, "\t// required path parameters: %s\n", strings.Join(pathParamsNeeded, ", "))
		}
		if hasBody(op.Method) {
			fmt.Fprintf(&b, "\treturn c.do(ctx, %q, %q, pathParams, body)\n}\n\n", op.Method, op.Path)
		} else {
			fmt.Fprintf(&b, "\treturn c.do(ctx, %q, %q, pathParams, nil)\n}\n\n", op.Method, op.Path)
		}
	}
	return map[string]string{"client.go": b.String()}
}

func hasBody(method string) bool {
	switch method {
	case "POST", "PUT", "PATCH":
		return true
	default:
		return false
	}
}

var pathParamRe = regexp.MustCompile(`\{([^}]+)\}`)

func extractPathParams(p string) []string {
	matches := pathParamRe.FindAllStringSubmatch(p, -1)
	out := make([]string, 0, len(matches))
	for _, m := range matches {
		out = append(out, m[1])
	}
	return out
}
