package codegen

import (
	"context"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"

	"github.com/Eisenmann/openapi-mocker/internal/domain/ports"
)

// JavaNativeAdapter generates Java server and client code natively from an
// OpenAPI contract, without external tooling. It implements
// ports.CodeGeneratorPort.
type JavaNativeAdapter struct{}

// NewJavaNativeAdapter creates a Java native adapter.
func NewJavaNativeAdapter() *JavaNativeAdapter {
	return &JavaNativeAdapter{}
}

// Supports reports whether this adapter supports the given language.
func (a *JavaNativeAdapter) Supports(lang ports.Language) bool {
	return lang == ports.LanguageJava
}

// Strategy returns the generation strategy used by this adapter.
func (a *JavaNativeAdapter) Strategy() ports.GenerationStrategy {
	return ports.StrategyNative
}

// Generate produces Java server and client files from the OpenAPI schema.
func (a *JavaNativeAdapter) Generate(
	ctx context.Context,
	req *ports.GenerationRequest,
) (*ports.GenerationResult, error) {
	doc, err := parseAndValidate(ctx, req.Schema.Content)
	if err != nil {
		return nil, err
	}

	pkgName := req.PackageName
	if pkgName == "" {
		pkgName = defaultPackageName
	}

	// Generate server files.
	serverFiles := generateJavaServer(doc, pkgName)

	// Generate client file.
	clientFiles := generateJavaClient(doc, pkgName)

	// Generate project files.
	projectFiles := map[string]string{
		"pom.xml":   generateJavaPom(pkgName),
		"README.md": generateJavaReadme(pkgName),
	}

	return buildNativeResult(req, ports.LanguageJava, serverFiles, clientFiles, projectFiles)
}

// generateJavaServer returns a set of files (name → content) with a Java
// HTTP server skeleton using the standard library com.sun.net.httpserver.
func generateJavaServer(doc *openapi3.T, pkgName string) map[string]string {
	ops := collectOperations(doc)

	return map[string]string{
		"ServerInterface.java":     generateJavaInterface(ops, pkgName),
		"Router.java":              generateJavaRouter(ops, pkgName),
		"UnimplementedServer.java": generateJavaUnimplemented(ops, pkgName),
		"Main.java":                generateJavaMain(pkgName),
	}
}

// generateJavaInterface produces the ServerInterface Java file.
func generateJavaInterface(ops []operationInfo, pkgName string) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	fmt.Fprintf(&b, "package %s;\n\n", pkgName)
	b.WriteString("import com.sun.net.httpserver.HttpExchange;\n\n")
	b.WriteString("// ServerInterface - implement this interface with your business logic.\n")
	b.WriteString("public interface ServerInterface {\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "    // %s %s %s\n", op.OpID, op.Method, op.Path)
		fmt.Fprintf(&b, "    void %s(HttpExchange exchange) throws Exception;\n", toJavaIdent(op.OpID))
	}

	b.WriteString("}\n")

	return b.String()
}

// generateJavaRouter produces the router Java file.
func generateJavaRouter(ops []operationInfo, pkgName string) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	fmt.Fprintf(&b, "package %s;\n\n", pkgName)
	b.WriteString("import com.sun.net.httpserver.HttpExchange;\n")
	b.WriteString("import com.sun.net.httpserver.HttpHandler;\n\n")
	b.WriteString("// NewRouter registers all contract operations on the ServerInterface implementation.\n")
	b.WriteString("public class Router implements HttpHandler {\n")
	b.WriteString("    private final ServerInterface impl;\n\n")
	b.WriteString("    public Router(ServerInterface impl) {\n")
	b.WriteString("        this.impl = impl;\n")
	b.WriteString("    }\n\n")
	b.WriteString("    @Override\n")
	b.WriteString("    public void handle(HttpExchange exchange) throws Exception {\n")
	b.WriteString("        String method = exchange.getRequestMethod().toUpperCase();\n")
	b.WriteString("        String path = exchange.getRequestURI().getPath();\n\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "        if (method.equals(%q) && path.startsWith(%q)) {\n", op.Method, op.Path)
		fmt.Fprintf(&b, "            impl.%s(exchange);\n", toJavaIdent(op.OpID))
		b.WriteString("            return;\n")
		b.WriteString("        }\n\n")
	}

	b.WriteString("        byte[] body = \"{\\\"error\\\": \\\"not found\\\"}\".getBytes();\n")
	b.WriteString("        exchange.getResponseHeaders().set(\"Content-Type\", \"application/json\");\n")
	b.WriteString("        exchange.sendResponseHeaders(404, body.length);\n")
	b.WriteString("        exchange.getResponseBody().write(body);\n")
	b.WriteString("        exchange.close();\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return b.String()
}

// generateJavaUnimplemented produces the sample implementation Java file.
func generateJavaUnimplemented(ops []operationInfo, pkgName string) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. THIS IS A SAMPLE implementation - customize for your needs.\n")
	fmt.Fprintf(&b, "package %s;\n\n", pkgName)
	b.WriteString("import com.sun.net.httpserver.HttpExchange;\n\n")
	b.WriteString("public class UnimplementedServer implements ServerInterface {\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "    @Override\n")
		fmt.Fprintf(&b, "    public void %s(HttpExchange exchange) throws Exception {\n", toJavaIdent(op.OpID))
		fmt.Fprintf(&b, "        byte[] body = (\"{\\\"error\\\": \\\"%s not implemented\\\"}\").getBytes();\n", op.OpID)
		b.WriteString("        exchange.getResponseHeaders().set(\"Content-Type\", \"application/json\");\n")
		b.WriteString("        exchange.sendResponseHeaders(501, body.length);\n")
		b.WriteString("        exchange.getResponseBody().write(body);\n")
		b.WriteString("        exchange.close();\n")
		b.WriteString("    }\n\n")
	}

	b.WriteString("}\n")

	return b.String()
}

// generateJavaMain produces the example server startup Java file.
func generateJavaMain(pkgName string) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. Example server startup.\n")
	fmt.Fprintf(&b, "package %s;\n\n", pkgName)
	b.WriteString("import com.sun.net.httpserver.HttpServer;\n")
	b.WriteString("import java.net.InetSocketAddress;\n\n")
	b.WriteString("public class Main {\n")
	b.WriteString("    public static void main(String[] args) throws Exception {\n")
	b.WriteString("        HttpServer server = HttpServer.create(new InetSocketAddress(8081), 0);\n")
	b.WriteString("        server.createContext(\"/\", new Router(new UnimplementedServer()));\n")
	b.WriteString("        server.start();\n")
	b.WriteString("        System.out.println(\"listening on :8081\");\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return b.String()
}

// generateJavaClient returns a set of files with a type-safe (by path and
// method) HTTP client for the contract.
func generateJavaClient(doc *openapi3.T, pkgName string) map[string]string {
	ops := collectOperations(doc)

	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	fmt.Fprintf(&b, "package %s;\n\n", pkgName)
	b.WriteString("import java.io.IOException;\n")
	b.WriteString("import java.net.URI;\n")
	b.WriteString("import java.net.http.HttpClient;\n")
	b.WriteString("import java.net.http.HttpRequest;\n")
	b.WriteString("import java.net.http.HttpResponse;\n")
	b.WriteString("import java.util.Map;\n\n")
	b.WriteString("public class Client {\n")
	b.WriteString("    private final HttpClient http;\n")
	b.WriteString("    private final String baseUrl;\n\n")
	b.WriteString("    public Client(String baseUrl) {\n")
	b.WriteString("        this.baseUrl = baseUrl.replaceAll(\"/$\", \"\");\n")
	b.WriteString("        this.http = HttpClient.newHttpClient();\n")
	b.WriteString("    }\n\n")
	b.WriteString("    private HttpResponse<String> doRequest(String method, String path, " +
		"Map<String, String> pathParams, String body) throws IOException, InterruptedException {\n")
	b.WriteString("        String url = path;\n")
	b.WriteString("        for (Map.Entry<String, String> e : pathParams.entrySet()) {\n")
	b.WriteString("            url = url.replace(\"{\" + e.getKey() + \"}\", e.getValue());\n")
	b.WriteString("        }\n\n")
	b.WriteString("        HttpRequest.Builder builder = HttpRequest.newBuilder()\n")
	b.WriteString("            .uri(URI.create(baseUrl + url))\n")
	b.WriteString("            .method(method, body == null ? " +
		"HttpRequest.BodyPublishers.noBody() : HttpRequest.BodyPublishers.ofString(body));\n")
	b.WriteString("        if (body != null) {\n")
	b.WriteString("            builder.header(\"Content-Type\", \"application/json\");\n")
	b.WriteString("        }\n\n")
	b.WriteString("        return http.send(builder.build(), HttpResponse.BodyHandlers.ofString());\n")
	b.WriteString("    }\n\n")

	for _, op := range ops {
		writeJavaClientMethod(&b, op)
	}

	b.WriteString("}\n")

	return map[string]string{"Client.java": b.String()}
}

// writeJavaClientMethod writes a single client method for an operation.
func writeJavaClientMethod(b *strings.Builder, op operationInfo) {
	pathParamsNeeded := extractPathParams(op.Path)
	fmt.Fprintf(b, "    // %s corresponds to %s %s\n", toJavaIdent(op.OpID), op.Method, op.Path)

	if hasBody(op.Method) {
		fmt.Fprintf(b, "    public HttpResponse<String> %s("+
			"Map<String, String> pathParams, String body) throws IOException, InterruptedException {\n", toJavaIdent(op.OpID))
	} else {
		fmt.Fprintf(b, "    public HttpResponse<String> %s("+
			"Map<String, String> pathParams) throws IOException, InterruptedException {\n", toJavaIdent(op.OpID))
	}

	b.WriteString("        ")

	if len(pathParamsNeeded) > 0 {
		fmt.Fprintf(b, "// required path parameters: %s\n", strings.Join(pathParamsNeeded, ", "))
		b.WriteString("        ")
	}

	if hasBody(op.Method) {
		fmt.Fprintf(b, "return doRequest(%q, %q, pathParams, body);\n", op.Method, op.Path)
	} else {
		fmt.Fprintf(b, "return doRequest(%q, %q, pathParams, null);\n", op.Method, op.Path)
	}

	b.WriteString("    }\n\n")
}

// generateJavaPom produces a pom.xml for the generated project.
func generateJavaPom(pkgName string) string {
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example</groupId>
  <artifactId>%s</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.1.0</version>
        <configuration>
          <mainClass>%s.Main</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
`, pkgName, pkgName)
}

// generateJavaReadme produces a README.md for the generated project.
func generateJavaReadme(pkgName string) string {
	return fmt.Sprintf(`# %s

Generated by openapi-mocker.

## Server

Run the example server:

`+"```bash"+`
mvn compile exec:java
`+"```"+`

## Client

Use the generated client:

`+"```java"+`
Client client = new Client("http://localhost:8081");
HttpResponse<String> response = client.getPets(Map.of());
`+"```"+`
`, pkgName)
}

// toJavaIdent converts a string to a valid Java identifier.
func toJavaIdent(s string) string {
	out := toGoIdent(s)
	if out == "" {
		return defaultOperationName
	}

	return out
}
