package codegen

import (
	"context"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"

	"github.com/Eisenmann/openapi-mocker/internal/domain/ports"
)

// PythonNativeAdapter generates Python server and client code natively from
// an OpenAPI contract, without external tooling. It implements
// ports.CodeGeneratorPort.
type PythonNativeAdapter struct{}

// NewPythonNativeAdapter creates a Python native adapter.
func NewPythonNativeAdapter() *PythonNativeAdapter {
	return &PythonNativeAdapter{}
}

// Supports reports whether this adapter supports the given language.
func (a *PythonNativeAdapter) Supports(lang ports.Language) bool {
	return lang == ports.LanguagePython
}

// Strategy returns the generation strategy used by this adapter.
func (a *PythonNativeAdapter) Strategy() ports.GenerationStrategy {
	return ports.StrategyNative
}

// Generate produces Python server and client files from the OpenAPI schema.
func (a *PythonNativeAdapter) Generate(
	ctx context.Context,
	req *ports.GenerationRequest,
) (*ports.GenerationResult, error) {
	doc, err := parseAndValidate(ctx, req.Schema.Content)
	if err != nil {
		return nil, err
	}

	pkgName := req.PackageName
	if pkgName == "" {
		pkgName = defaultPackageName
	}

	// Generate server files.
	serverFiles := generatePyServer(doc, pkgName)

	// Generate client file.
	clientFiles := generatePyClient(doc, pkgName)

	// Combine into GeneratedFile list.
	var files []ports.GeneratedFile
	for name, content := range serverFiles {
		files = append(files, ports.GeneratedFile{
			Path:    req.OutputPath + "/server/" + name,
			Content: []byte(content),
			IsNew:   true,
		})
	}

	for name, content := range clientFiles {
		files = append(files, ports.GeneratedFile{
			Path:    req.OutputPath + "/client/" + name,
			Content: []byte(content),
			IsNew:   true,
		})
	}

	// Generate requirements.txt.
	requirements := generatePyRequirements()

	files = append(files, ports.GeneratedFile{
		Path:    req.OutputPath + "/requirements.txt",
		Content: []byte(requirements),
		IsNew:   true,
	})

	// Generate README.md.
	readme := generatePyReadme(pkgName)

	files = append(files, ports.GeneratedFile{
		Path:    req.OutputPath + "/README.md",
		Content: []byte(readme),
		IsNew:   true,
	})

	return &ports.GenerationResult{
		Files:      files,
		Language:   ports.LanguagePython,
		Strategy:   ports.StrategyNative,
		Warnings:   []string{},
		CICDConfig: nil,
	}, nil
}

// generatePyServer returns a set of files (name → content) with a Python
// HTTP server skeleton using the standard library http.server module.
func generatePyServer(doc *openapi3.T, _ string) map[string]string {
	ops := collectOperations(doc)

	return map[string]string{
		"server_interface.py": generatePyInterface(ops),
		"router.py":           generatePyRouter(ops),
		"unimplemented.py":    generatePyUnimplemented(ops),
		"server.py":           generatePyServerMain(),
	}
}

// generatePyInterface produces the ServerInterface Python file.
func generatePyInterface(ops []operationInfo) string {
	var b strings.Builder
	b.WriteString("# Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	b.WriteString("from abc import ABC, abstractmethod\n")
	b.WriteString("from http.server import BaseHTTPRequestHandler\n\n")
	b.WriteString("# ServerInterface - implement this interface with your business logic.\n")
	b.WriteString("class ServerInterface(ABC):\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "    # %s %s %s\n", op.OpID, op.Method, op.Path)
		fmt.Fprintf(&b, "    @abstractmethod\n")
		fmt.Fprintf(&b, "    def %s(self, handler: BaseHTTPRequestHandler) -> None:\n", toPyIdent(op.OpID))
		b.WriteString("        pass\n\n")
	}

	return b.String()
}

// generatePyRouter produces the router Python file.
func generatePyRouter(ops []operationInfo) string {
	var b strings.Builder
	b.WriteString("# Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	b.WriteString("from http.server import BaseHTTPRequestHandler\n")
	b.WriteString("from .server_interface import ServerInterface\n\n")
	b.WriteString("# NewRouter registers all contract operations on the ServerInterface implementation.\n")
	b.WriteString("def NewRouter(impl: ServerInterface):\n")
	b.WriteString("    def handler(req: BaseHTTPRequestHandler) -> None:\n")
	b.WriteString("        method = req.command.upper()\n")
	b.WriteString("        path = req.path.split('?')[0]\n\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "        if method == %q and path.startswith(%q):\n", op.Method, op.Path)
		fmt.Fprintf(&b, "            impl.%s(req)\n", toPyIdent(op.OpID))
		b.WriteString("            return\n\n")
	}

	b.WriteString("        req.send_response(404)\n")
	b.WriteString("        req.send_header('Content-Type', 'application/json')\n")
	b.WriteString("        req.end_headers()\n")
	b.WriteString("        req.wfile.write(b'{\"error\": \"not found\"}')\n")
	b.WriteString("    return handler\n")

	return b.String()
}

// generatePyUnimplemented produces the sample implementation Python file.
func generatePyUnimplemented(ops []operationInfo) string {
	var b strings.Builder
	b.WriteString("# Code generated by openapi-mocker. THIS IS A SAMPLE implementation - customize for your needs.\n")
	b.WriteString("import json\n")
	b.WriteString("from http.server import BaseHTTPRequestHandler\n")
	b.WriteString("from .server_interface import ServerInterface\n\n")
	b.WriteString("class UnimplementedServer(ServerInterface):\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "    def %s(self, handler: BaseHTTPRequestHandler) -> None:\n", toPyIdent(op.OpID))
		b.WriteString("        handler.send_response(501)\n")
		b.WriteString("        handler.send_header('Content-Type', 'application/json')\n")
		b.WriteString("        handler.end_headers()\n")
		fmt.Fprintf(&b, "        handler.wfile.write(json.dumps({'error': %q}).encode())\n", op.OpID+" not implemented")
		b.WriteString("\n")
	}

	return b.String()
}

// generatePyServerMain produces the example server startup Python file.
func generatePyServerMain() string {
	var b strings.Builder
	b.WriteString("# Code generated by openapi-mocker. Example server startup.\n")
	b.WriteString("from http.server import HTTPServer, BaseHTTPRequestHandler\n")
	b.WriteString("from .router import NewRouter\n")
	b.WriteString("from .unimplemented import UnimplementedServer\n\n")
	b.WriteString("class Handler(BaseHTTPRequestHandler):\n")
	b.WriteString("    def do_GET(self):\n")
	b.WriteString("        NewRouter(UnimplementedServer())(self)\n")
	b.WriteString("    def do_POST(self):\n")
	b.WriteString("        NewRouter(UnimplementedServer())(self)\n")
	b.WriteString("    def do_PUT(self):\n")
	b.WriteString("        NewRouter(UnimplementedServer())(self)\n")
	b.WriteString("    def do_PATCH(self):\n")
	b.WriteString("        NewRouter(UnimplementedServer())(self)\n")
	b.WriteString("    def do_DELETE(self):\n")
	b.WriteString("        NewRouter(UnimplementedServer())(self)\n")
	b.WriteString("    def log_message(self, format, *args):\n")
	b.WriteString("        pass\n\n")
	b.WriteString("if __name__ == '__main__':\n")
	b.WriteString("    server = HTTPServer(('localhost', 8081), Handler)\n")
	b.WriteString("    print('listening on :8081')\n")
	b.WriteString("    server.serve_forever()\n")

	return b.String()
}

// generatePyClient returns a set of files with a type-safe (by path and
// method) HTTP client for the contract.
func generatePyClient(doc *openapi3.T, _ string) map[string]string {
	ops := collectOperations(doc)

	var b strings.Builder
	b.WriteString("# Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	b.WriteString("import json\n")
	b.WriteString("from typing import Any, Dict, Optional\n")
	b.WriteString("from urllib.request import Request, urlopen\n\n")
	b.WriteString("class Client:\n")
	b.WriteString("    def __init__(self, base_url: str):\n")
	b.WriteString("        self.base_url = base_url.rstrip('/')\n\n")
	b.WriteString("    def _do(self, method: str, path: str, path_params: Dict[str, str], body: Optional[Any] = None):\n")
	b.WriteString("        url = path\n")
	b.WriteString("        for k, v in path_params.items():\n")
	b.WriteString("            url = url.replace('{' + k + '}', v)\n")
	b.WriteString("        data = None\n")
	b.WriteString("        headers = {}\n")
	b.WriteString("        if body is not None:\n")
	b.WriteString("            data = json.dumps(body).encode()\n")
	b.WriteString("            headers['Content-Type'] = 'application/json'\n")
	b.WriteString("        req = Request(self.base_url + url, data=data, headers=headers, method=method)\n")
	b.WriteString("        with urlopen(req) as resp:\n")
	b.WriteString("            return resp.status, resp.read()\n\n")

	for _, op := range ops {
		pathParamsNeeded := extractPathParams(op.Path)
		fmt.Fprintf(&b, "    # %s corresponds to %s %s\n", toPyIdent(op.OpID), op.Method, op.Path)

		if hasBody(op.Method) {
			fmt.Fprintf(&b, "    def %s(self, path_params: Dict[str, str], body: Any = None):\n", toPyIdent(op.OpID))
		} else {
			fmt.Fprintf(&b, "    def %s(self, path_params: Optional[Dict[str, str]] = None):\n", toPyIdent(op.OpID))
		}

		if len(pathParamsNeeded) > 0 {
			fmt.Fprintf(&b, "        # required path parameters: %s\n", strings.Join(pathParamsNeeded, ", "))
		}

		if hasBody(op.Method) {
			fmt.Fprintf(&b, "        return self._do(%q, %q, path_params or {}, body)\n", op.Method, op.Path)
		} else {
			fmt.Fprintf(&b, "        return self._do(%q, %q, path_params or {})\n", op.Method, op.Path)
		}

		b.WriteString("\n")
	}

	return map[string]string{"client.py": b.String()}
}

// generatePyRequirements produces a requirements.txt for the generated project.
func generatePyRequirements() string {
	return "# Generated by openapi-mocker. No external dependencies required.\n"
}

// generatePyReadme produces a README.md for the generated project.
func generatePyReadme(pkgName string) string {
	return fmt.Sprintf(`# %s

Generated by openapi-mocker.

## Server

Run the example server:

`+"```bash"+`
python -m server.server
`+"```"+`

## Client

Use the generated client:

`+"```python"+`
from client.client import Client

client = Client("http://localhost:8081")
status, body = client.get_pets({})
`+"```"+`
`, pkgName)
}

// toPyIdent converts a string to a valid Python identifier.
func toPyIdent(s string) string {
	out := toGoIdent(s)
	if out == "" {
		return "operation"
	}

	// Python identifiers are lowercase by convention.
	return strings.ToLower(out[:1]) + out[1:]
}
