package codegen

import (
	"context"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"

	"github.com/Eisenmann/openapi-mocker/internal/domain/ports"
)

// RustNativeAdapter generates Rust server and client code natively from an
// OpenAPI contract, without external tooling. It implements
// ports.CodeGeneratorPort.
type RustNativeAdapter struct{}

// NewRustNativeAdapter creates a Rust native adapter.
func NewRustNativeAdapter() *RustNativeAdapter {
	return &RustNativeAdapter{}
}

// Supports reports whether this adapter supports the given language.
func (a *RustNativeAdapter) Supports(lang ports.Language) bool {
	return lang == ports.LanguageRust
}

// Strategy returns the generation strategy used by this adapter.
func (a *RustNativeAdapter) Strategy() ports.GenerationStrategy {
	return ports.StrategyNative
}

// Generate produces Rust server and client files from the OpenAPI schema.
func (a *RustNativeAdapter) Generate(
	ctx context.Context,
	req *ports.GenerationRequest,
) (*ports.GenerationResult, error) {
	doc, err := parseAndValidate(ctx, req.Schema.Content)
	if err != nil {
		return nil, err
	}

	pkgName := req.PackageName
	if pkgName == "" {
		pkgName = defaultPackageName
	}

	// Generate server files.
	serverFiles := generateRustServer(doc, pkgName)

	// Generate client file.
	clientFiles := generateRustClient(doc, pkgName)

	// Generate project files.
	projectFiles := map[string]string{
		"Cargo.toml": generateRustCargo(pkgName),
		"README.md":  generateRustReadme(pkgName),
	}

	return buildNativeResult(req, ports.LanguageRust, serverFiles, clientFiles, projectFiles)
}

// generateRustServer returns a set of files (name → content) with a Rust
// HTTP server skeleton using the standard library TcpListener.
func generateRustServer(doc *openapi3.T, _ string) map[string]string {
	ops := collectOperations(doc)

	return map[string]string{
		"server_interface.rs": generateRustInterface(ops),
		"router.rs":           generateRustRouter(ops),
		"unimplemented.rs":    generateRustUnimplemented(ops),
		"main.rs":             generateRustMain(),
	}
}

// generateRustInterface produces the ServerInterface Rust file.
func generateRustInterface(ops []operationInfo) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	b.WriteString("// ServerInterface - implement this trait with your business logic.\n")
	b.WriteString("pub trait ServerInterface {\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "    // %s %s %s\n", op.OpID, op.Method, op.Path)
		fmt.Fprintf(&b, "    fn %s(&self, req: &str) -> String;\n", toRustIdent(op.OpID))
	}

	b.WriteString("}\n")

	return b.String()
}

// generateRustRouter produces the router Rust file.
func generateRustRouter(ops []operationInfo) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	b.WriteString("use crate::server_interface::ServerInterface;\n\n")
	b.WriteString("// NewRouter registers all contract operations on the ServerInterface implementation.\n")
	b.WriteString("pub fn handle(impl_: &dyn ServerInterface, method: &str, path: &str) -> String {\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "    if method == %q && path.starts_with(%q) {\n", op.Method, op.Path)
		fmt.Fprintf(&b, "        return impl_.%s(path);\n", toRustIdent(op.OpID))
		b.WriteString("    }\n\n")
	}

	b.WriteString("    format!(\"{{\\\"error\\\": \\\"not found\\\"}}\")\n")
	b.WriteString("}\n")

	return b.String()
}

// generateRustUnimplemented produces the sample implementation Rust file.
func generateRustUnimplemented(ops []operationInfo) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. THIS IS A SAMPLE implementation - customize for your needs.\n")
	b.WriteString("use crate::server_interface::ServerInterface;\n\n")
	b.WriteString("pub struct UnimplementedServer;\n\n")
	b.WriteString("impl ServerInterface for UnimplementedServer {\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "    fn %s(&self, _req: &str) -> String {\n", toRustIdent(op.OpID))
		fmt.Fprintf(&b, "        format!(\"{{\\\"error\\\": \\\"%s not implemented\\\"}}\")\n", op.OpID)
		b.WriteString("    }\n\n")
	}

	b.WriteString("}\n")

	return b.String()
}

// generateRustMain produces the example server startup Rust file.
func generateRustMain() string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. Example server startup.\n")
	b.WriteString("mod server_interface;\n")
	b.WriteString("mod router;\n")
	b.WriteString("mod unimplemented;\n\n")
	b.WriteString("use std::io::{Read, Write};\n")
	b.WriteString("use std::net::TcpListener;\n\n")
	b.WriteString("fn main() {\n")
	b.WriteString("    let listener = TcpListener::bind(\"127.0.0.1:8081\").unwrap();\n")
	b.WriteString("    println!(\"listening on :8081\");\n\n")
	b.WriteString("    let impl_ = unimplemented::UnimplementedServer;\n\n")
	b.WriteString("    for stream in listener.incoming() {\n")
	b.WriteString("        let mut stream = stream.unwrap();\n")
	b.WriteString("        let mut buf = [0u8; 4096];\n")
	b.WriteString("        let n = stream.read(&mut buf).unwrap();\n")
	b.WriteString("        let request = String::from_utf8_lossy(&buf[..n]);\n")
	b.WriteString("        let mut lines = request.lines();\n")
	b.WriteString("        let request_line = lines.next().unwrap_or(\"\");\n")
	b.WriteString("        let mut parts = request_line.split_whitespace();\n")
	b.WriteString("        let method = parts.next().unwrap_or(\"GET\");\n")
	b.WriteString("        let path = parts.next().unwrap_or(\"/\");\n")
	b.WriteString("        let body = router::handle(&impl_, method, path);\n")
	b.WriteString("        let response = format!(\"HTTP/1.1 200 OK\\r\\n" +
		"Content-Type: application/json\\r\\n\\r\\n{}\", body);\n")
	b.WriteString("        stream.write_all(response.as_bytes()).unwrap();\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return b.String()
}

// generateRustClient returns a set of files with a type-safe (by path and
// method) HTTP client for the contract.
func generateRustClient(doc *openapi3.T, _ string) map[string]string {
	ops := collectOperations(doc)

	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	b.WriteString("use std::collections::HashMap;\n\n")
	b.WriteString("pub struct Client {\n")
	b.WriteString("    base_url: String,\n")
	b.WriteString("}\n\n")
	b.WriteString("impl Client {\n")
	b.WriteString("    pub fn new(base_url: &str) -> Self {\n")
	b.WriteString("        Self { base_url: base_url.trim_end_matches('/').to_string() }\n")
	b.WriteString("    }\n\n")
	b.WriteString("    fn do_request(&self, method: &str, path: &str, " +
		"path_params: &HashMap<String, String>, body: Option<&str>) -> String {\n")
	b.WriteString("        let mut url = path.to_string();\n")
	b.WriteString("        for (k, v) in path_params {\n")
	b.WriteString("            url = url.replace(&format!(\"{{{}}}\", k), v);\n")
	b.WriteString("        }\n")
	b.WriteString("        let _ = method;\n")
	b.WriteString("        let _ = body;\n")
	b.WriteString("        format!(\"{} {}\", self.base_url, url)\n")
	b.WriteString("    }\n\n")

	for _, op := range ops {
		writeRustClientMethod(&b, op)
	}

	b.WriteString("}\n")

	return map[string]string{"client.rs": b.String()}
}

// writeRustClientMethod writes a single client method for an operation.
func writeRustClientMethod(b *strings.Builder, op operationInfo) {
	pathParamsNeeded := extractPathParams(op.Path)
	fmt.Fprintf(b, "    // %s corresponds to %s %s\n", toRustIdent(op.OpID), op.Method, op.Path)

	if hasBody(op.Method) {
		fmt.Fprintf(b, "    pub fn %s(&self, path_params: &HashMap<String, String>, "+
			"body: &str) -> String {\n", toRustIdent(op.OpID))
	} else {
		fmt.Fprintf(b, "    pub fn %s(&self, path_params: &HashMap<String, String>) -> String {\n", toRustIdent(op.OpID))
	}

	b.WriteString("        ")

	if len(pathParamsNeeded) > 0 {
		fmt.Fprintf(b, "// required path parameters: %s\n", strings.Join(pathParamsNeeded, ", "))
		b.WriteString("        ")
	}

	if hasBody(op.Method) {
		fmt.Fprintf(b, "self.do_request(%q, %q, path_params, Some(body))\n", op.Method, op.Path)
	} else {
		fmt.Fprintf(b, "self.do_request(%q, %q, path_params, None)\n", op.Method, op.Path)
	}

	b.WriteString("    }\n\n")
}

// generateRustCargo produces a Cargo.toml for the generated project.
func generateRustCargo(pkgName string) string {
	return fmt.Sprintf(`[package]
name = %q
version = "1.0.0"
edition = "2021"

[dependencies]
`, pkgName)
}

// generateRustReadme produces a README.md for the generated project.
func generateRustReadme(pkgName string) string {
	return fmt.Sprintf(`# %s

Generated by openapi-mocker.

## Server

Run the example server:

`+"```bash"+`
cargo run
`+"```"+`

## Client

Use the generated client:

`+"```rust"+`
let client = Client::new("http://localhost:8081");
let response = client.get_pets(&HashMap::new());
`+"```"+`
`, pkgName)
}

// toRustIdent converts a string to a valid Rust identifier.
func toRustIdent(s string) string {
	out := toGoIdent(s)
	if out == "" {
		return defaultOperationName
	}

	// Rust identifiers are snake_case by convention.
	return toSnakeCase(out)
}

// toSnakeCase converts a CamelCase string to snake_case.
func toSnakeCase(s string) string {
	var b strings.Builder

	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}

			b.WriteRune(r + ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}

	return b.String()
}
