package codegen

import (
	"context"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"

	"github.com/Eisenmann/openapi-mocker/internal/domain/ports"
)

// TypeScriptNativeAdapter generates TypeScript server and client code
// natively from an OpenAPI contract, without external tooling. It implements
// ports.CodeGeneratorPort.
type TypeScriptNativeAdapter struct{}

// NewTypeScriptNativeAdapter creates a TypeScript native adapter.
func NewTypeScriptNativeAdapter() *TypeScriptNativeAdapter {
	return &TypeScriptNativeAdapter{}
}

// Supports reports whether this adapter supports the given language.
func (a *TypeScriptNativeAdapter) Supports(lang ports.Language) bool {
	return lang == ports.LanguageTypeScript
}

// Strategy returns the generation strategy used by this adapter.
func (a *TypeScriptNativeAdapter) Strategy() ports.GenerationStrategy {
	return ports.StrategyNative
}

// Generate produces TypeScript server and client files from the OpenAPI schema.
func (a *TypeScriptNativeAdapter) Generate(
	ctx context.Context,
	req *ports.GenerationRequest,
) (*ports.GenerationResult, error) {
	doc, err := parseAndValidate(ctx, req.Schema.Content)
	if err != nil {
		return nil, err
	}

	pkgName := req.PackageName
	if pkgName == "" {
		pkgName = defaultPackageName
	}

	// Generate server files.
	serverFiles := generateTSServer(doc, pkgName)

	// Generate client file.
	clientFiles := generateTSClient(doc, pkgName)

	// Combine into GeneratedFile list.
	var files []ports.GeneratedFile
	for name, content := range serverFiles {
		files = append(files, ports.GeneratedFile{
			Path:    req.OutputPath + "/server/" + name,
			Content: []byte(content),
			IsNew:   true,
		})
	}

	for name, content := range clientFiles {
		files = append(files, ports.GeneratedFile{
			Path:    req.OutputPath + "/client/" + name,
			Content: []byte(content),
			IsNew:   true,
		})
	}

	// Generate package.json.
	packageJSON := generateTSPackageJSON(pkgName)

	files = append(files, ports.GeneratedFile{
		Path:    req.OutputPath + "/package.json",
		Content: []byte(packageJSON),
		IsNew:   true,
	})

	// Generate tsconfig.json.
	tsconfig := generateTSTsconfig()

	files = append(files, ports.GeneratedFile{
		Path:    req.OutputPath + "/tsconfig.json",
		Content: []byte(tsconfig),
		IsNew:   true,
	})

	return &ports.GenerationResult{
		Files:      files,
		Language:   ports.LanguageTypeScript,
		Strategy:   ports.StrategyNative,
		Warnings:   []string{},
		CICDConfig: nil,
	}, nil
}

// generateTSServer returns a set of files (name → content) with a TypeScript
// HTTP server skeleton using the standard Node.js http module.
func generateTSServer(doc *openapi3.T, _ string) map[string]string {
	ops := collectOperations(doc)

	return map[string]string{
		"server_interface.ts": generateTSInterface(ops),
		"router.ts":           generateTSRouter(ops),
		"unimplemented.ts":    generateTSUnimplemented(ops),
		"server.ts":           generateTSServerMain(),
	}
}

// generateTSInterface produces the ServerInterface TypeScript file.
func generateTSInterface(ops []operationInfo) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	b.WriteString("import { IncomingMessage, ServerResponse } from 'http';\n\n")
	b.WriteString("// ServerInterface - implement this interface with your business logic.\n")
	b.WriteString("export interface ServerInterface {\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "  // %s %s %s\n", op.OpID, op.Method, op.Path)
		fmt.Fprintf(&b, "  %s(req: IncomingMessage, res: ServerResponse): void;\n", toTSIdent(op.OpID))
	}

	b.WriteString("}\n")

	return b.String()
}

// generateTSRouter produces the router TypeScript file.
func generateTSRouter(ops []operationInfo) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	b.WriteString("import { IncomingMessage, ServerResponse } from 'http';\n")
	b.WriteString("import { ServerInterface } from './server_interface';\n\n")
	b.WriteString("// NewRouter registers all contract operations on the ServerInterface implementation.\n")
	b.WriteString("export function NewRouter(impl: ServerInterface) {\n")
	b.WriteString("  return (req: IncomingMessage, res: ServerResponse) => {\n")
	b.WriteString("    const url = req.url || '/';\n")
	b.WriteString("    const method = (req.method || 'GET').toUpperCase();\n\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "    if (method === %q && url.startsWith(%q)) {\n", op.Method, op.Path)
		fmt.Fprintf(&b, "      impl.%s(req, res);\n", toTSIdent(op.OpID))
		b.WriteString("      return;\n")
		b.WriteString("    }\n\n")
	}

	b.WriteString("    res.statusCode = 404;\n")
	b.WriteString("    res.setHeader('Content-Type', 'application/json');\n")
	b.WriteString("    res.end(JSON.stringify({ error: 'not found' }));\n")
	b.WriteString("  };\n")
	b.WriteString("}\n")

	return b.String()
}

// generateTSUnimplemented produces the sample implementation TypeScript file.
func generateTSUnimplemented(ops []operationInfo) string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. THIS IS A SAMPLE implementation - customize for your needs.\n")
	b.WriteString("import { IncomingMessage, ServerResponse } from 'http';\n")
	b.WriteString("import { ServerInterface } from './server_interface';\n\n")
	b.WriteString("export class UnimplementedServer implements ServerInterface {\n")

	for _, op := range ops {
		fmt.Fprintf(&b, "  %s(req: IncomingMessage, res: ServerResponse): void {\n", toTSIdent(op.OpID))
		b.WriteString("    res.statusCode = 501;\n")
		b.WriteString("    res.setHeader('Content-Type', 'application/json');\n")
		fmt.Fprintf(&b, "    res.end(JSON.stringify({ error: %q }));\n", op.OpID+" not implemented")
		b.WriteString("  }\n\n")
	}

	b.WriteString("}\n")

	return b.String()
}

// generateTSServerMain produces the example server startup TypeScript file.
func generateTSServerMain() string {
	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. Example server startup.\n")
	b.WriteString("import { createServer } from 'http';\n")
	b.WriteString("import { NewRouter } from './router';\n")
	b.WriteString("import { UnimplementedServer } from './unimplemented';\n\n")
	b.WriteString("const server = createServer(NewRouter(new UnimplementedServer()));\n")
	b.WriteString("server.listen(8081, () => console.log('listening on :8081'));\n")

	return b.String()
}

// generateTSClient returns a set of files with a type-safe (by path and
// method) HTTP client for the contract.
func generateTSClient(doc *openapi3.T, _ string) map[string]string {
	ops := collectOperations(doc)

	var b strings.Builder
	b.WriteString("// Code generated by openapi-mocker. DO NOT EDIT manually if you plan to regenerate.\n")
	b.WriteString("export class Client {\n")
	b.WriteString("  baseURL: string;\n\n")
	b.WriteString("  constructor(baseURL: string) {\n")
	b.WriteString("    this.baseURL = baseURL.replace(/\\/$/, '');\n")
	b.WriteString("  }\n\n")
	b.WriteString("  private async do(method: string, path: string, " +
		"pathParams: Record<string, string>, body?: unknown): Promise<Response> {\n")
	b.WriteString("    let url = path;\n")
	b.WriteString("    for (const [k, v] of Object.entries(pathParams)) {\n")
	b.WriteString("      url = url.replace(`{${k}}`, v);\n")
	b.WriteString("    }\n")
	b.WriteString("    const init: RequestInit = { method };\n")
	b.WriteString("    if (body !== undefined) {\n")
	b.WriteString("      init.headers = { 'Content-Type': 'application/json' };\n")
	b.WriteString("      init.body = JSON.stringify(body);\n")
	b.WriteString("    }\n")
	b.WriteString("    return fetch(this.baseURL + url, init);\n")
	b.WriteString("  }\n\n")

	for _, op := range ops {
		pathParamsNeeded := extractPathParams(op.Path)
		fmt.Fprintf(&b, "  // %s corresponds to %s %s\n", toTSIdent(op.OpID), op.Method, op.Path)

		if hasBody(op.Method) {
			fmt.Fprintf(&b, "  async %s(pathParams: Record<string, string>, "+
				"body: unknown): Promise<Response> {\n", toTSIdent(op.OpID))
		} else {
			fmt.Fprintf(&b, "  async %s(pathParams: Record<string, string> = {}): Promise<Response> {\n", toTSIdent(op.OpID))
		}

		if len(pathParamsNeeded) > 0 {
			fmt.Fprintf(&b, "    // required path parameters: %s\n", strings.Join(pathParamsNeeded, ", "))
		}

		if hasBody(op.Method) {
			fmt.Fprintf(&b, "    return this.do(%q, %q, pathParams, body);\n", op.Method, op.Path)
		} else {
			fmt.Fprintf(&b, "    return this.do(%q, %q, pathParams);\n", op.Method, op.Path)
		}

		b.WriteString("  }\n\n")
	}

	b.WriteString("}\n")

	return map[string]string{"client.ts": b.String()}
}

// generateTSPackageJSON produces a package.json for the generated project.
func generateTSPackageJSON(pkgName string) string {
	return fmt.Sprintf(`{
  "name": %q,
  "version": "1.0.0",
  "description": "Generated by openapi-mocker",
  "main": "server/server.ts",
  "scripts": {
    "build": "tsc",
    "start": "node dist/server/server.js"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/node": "^20.0.0"
  }
}
`, pkgName)
}

// generateTSTsconfig produces a tsconfig.json for the generated project.
func generateTSTsconfig() string {
	return `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./dist",
    "rootDir": ".",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["server/**/*.ts", "client/**/*.ts"]
}
`
}

// toTSIdent converts a string to a valid TypeScript identifier.
func toTSIdent(s string) string {
	out := toGoIdent(s)
	if out == "" {
		return defaultOperationName
	}

	return out
}
