module github.com/example/openapi-mocker

go 1.26.5

// go.sum is intentionally absent — it will be generated by `go mod tidy`
// on the first build (requires network access). kin-openapi can parse both
// JSON and YAML contracts on its own, so a separate YAML dependency is not
// needed by this application.
require github.com/getkin/kin-openapi v0.128.0

require (
	github.com/go-openapi/jsonpointer v0.21.0 // indirect
	github.com/go-openapi/swag v0.23.0 // indirect
	github.com/invopop/yaml v0.3.1 // indirect
	github.com/josharian/intern v1.0.0 // indirect
	github.com/mailru/easyjson v0.7.7 // indirect
	github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826 // indirect
	github.com/perimeterx/marshmallow v1.1.5 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
